### ISSUE TITLE
NullPointerException because "this.iaImageUseAll" is null

### ISSUE THREAD

**Issue by Classsic36** [Fox2Code/ItemsAdderEmojiFixer#1]
Plugin does not load due to a NullPointerException

Error: https://pastebin.com/LdUcF5GF

Paper version: git-Paper-28 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: b0eb4e0)
ItemsAdder version: 3.2.0b-beta4

**Comment by Fox2Code** [comment]
Fixed with https://github.com/Fox2Code/ItemsAdderEmojiFixer/commit/bc1922e3b799849545d7daad82823a48165c4fb2 Thx for reporting the bug.
